apiVersion: apps/v1
kind: Deployment
metadata:
  name: winterhack-kestra
  labels:
    app: winterhack-kestra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: winterhack-kestra
  template:
    metadata:
      labels:
        app: winterhack-kestra
    spec:
      containers:
      - name: winterhack-kestra
        # Update to the correct image name in ACR
        image: kestraacr.azurecr.io/my-node-app:latest
        ports:
        - containerPort: 5001
        # Mount environment variables from existing secret
        envFrom:
        - secretRef:
            name: my-app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: winterhack-kestra-service
spec:
  selector:
    app: winterhack-kestra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
