deployment.yaml
@@ -1,44 +1,81 @@
apiVersion: apps/v1
kind: Deployment
metadata:
  name: winterhack-kestra
  labels:
    app: winterhack-kestra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: winterhack-kestra
  template:
    metadata:
      labels:
        app: winterhack-kestra
    spec:
      containers:
      - name: winterhack-kestra
        image: kestraacr.azurecr.io/my-node-app:latest  
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: my-app-secrets  
        - secretRef:
            name: azure-sp-secret
      imagePullSecrets:
      - name: acr-secret  
---
apiVersion: v1
kind: Service
metadata:
  name: winterhack-kestra-service
spec:
  selector:
    app: winterhack-kestra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer