apiVersion: v1
kind: Service
metadata:
  name: winterhack-kestra-service
spec:
  selector:
    app: winterhack-kestra
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
